### ISSUE TITLE
#Error: found in Chart.yaml, but missing in charts/ directory: kafka

### ISSUE THREAD

**Issue by CaoYunzhou** [metersphere/helm-chart#11]
### 定义的helm template 缺少kafka的定义

**Comment by easayliu** [comment]
执行
```
helm repo add bitnami https://charts.bitnami.com/bitnami
```

**Comment by CaoYunzhou** [comment]
定义的helm chat里面缺少测试资源池

Q：jmeter运行在某个pods里面嘛？
Q:   系统设置-> 设置 -> 系统 -> 测试资源池里面默认的资源地址池是没有的，node-controller和测试node的pods在helm里面没有体现，docker-compose版本是有的
Q: mock的配置的端口，是否通过svc进行暴露？mock的网络在k8s里面如何配置

**Comment by wangzhen-fit2cloud** [comment]
> 定义的helm chat里面缺少测试资源池
> 
> Q：jmeter运行在某个pods里面嘛？ Q: 系统设置-> 设置 -> 系统 -> 测试资源池里面默认的资源地址池是没有的，node-controller和测试node的pods在helm里面没有体现，docker-compose版本是有的 Q: mock的配置的端口，是否通过svc进行暴露？mock的网络在k8s里面如何配置

你好，目前在 K8S 环境中有两种方式配置资源池，最近更新的 chart 也增加了 node-controller 对应的配置
- Node 类型资源池：node-controller 以 pod 形式运行在 k8s 中，并且挂载对应节点的 docker socket ，node-controller 通过调用所在节点的 docker 接口，启动 JMeter 容器（非pod）
- K8S 类型资源池（X-Pack）：MeterSphere 直接调用 K8S API 创建对应的测试 Job

如果是 HTTP 接口的 Mock，端口与应用服务端口是一致的，能访问应用的 Web 页面就可以访问到 Mock 接口。在 chart 中已经配置了 svc 及 ingress；
如果是 TCP 接口的 Mock，需要单独把对应项目的 TCP Mock 端口暴露下，可以通过 node-port 形式的 svc 暴露，在 chart 中还没有增加对应配置，需要手动处理下。
