### ISSUE TITLE
metersphere-node-controller.yaml中configmap的引用有问题

### ISSUE THREAD

**Issue by andy2046cynthia** [metersphere/helm-chart#16]
helm-chart/charts/metersphere/templates/03-modules/metersphere-node-controller.yaml 中关于configmap的使用有问题：
volumes:
        - configMap:
            defaultMode: 420
            name: metersphere-config
            items:
            - key: node-controller.properties #这个地方和下面应该颠倒过来
              path: metersphere.properties

**Comment by wangzhen-fit2cloud** [comment]
你好，感谢反馈。贴出来的部分没有问题，问题是在 configmap 的 yaml 中没有添加 node-controller 的部分，已修改。
