### ISSUE TITLE
helm名称与文件夹名称不一致 helm lint fail

### ISSUE THREAD

**Issue by tankouei** [metersphere/helm-chart#2]
[ERROR] Chart.yaml: directory name (metersphere) and chart name (metersphere-chart) must be the same

**Comment by nanjofan** [comment]
<img width="661" alt="企业微信截图_1611210148892" src="https://user-images.githubusercontent.com/68266519/105302909-6042b900-5bf6-11eb-838e-ae9b79aa49e6.png">
在安装的时候报错说缺少了kafka的yaml配置文件，怎么解决呀

**Comment by tankouei** [comment]
> <img alt="企业微信截图_1611210148892" width="661" src="https://user-images.githubusercontent.com/68266519/105302909-6042b900-5bf6-11eb-838e-ae9b79aa49e6.png">
> 
> 在安装的时候报错说缺少了kafka的yaml配置文件，怎么解决呀

你这个是缺少依赖。把https://charts.bitnami.com/bitnami中的kafka下载到你charts目录中

命令：
helm dependency update
自动下载的 
![image](https://user-images.githubusercontent.com/28681545/106113180-21c67480-6189-11eb-9120-c312ff843168.png)
