### ISSUE TITLE
请问ms-node-controller是怎么部署的，看了yaml文件都没有这个，k8s部署如何扩展压测的资源池节点呢

### ISSUE THREAD

**Issue by VanLiuZhi** [metersphere/helm-chart#6]
请问ms-node-controller是怎么部署的，看了yaml文件都没有这个，k8s部署如何扩展压测的资源池节点呢

是不是企业版才提供的功能？

**Comment by wangzhen-fit2cloud** [comment]
你好，因为 node-controller 是通过调用本地 docker 客户端的方式启动性能测试的，目前不支持部署在 k8s 集群中。
对于 k8s 集群执行接口、性能测试现在是通过直接调用 k8s 接口完成的，是企业版中的功能。
